{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-config
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
data:
  # Add any configuration files or properties here
  BACKEND_SERVICE_HOST: {{ include "todo-chatbot.component.fullname" (list "backend" .) }}
  BACKEND_SERVICE_PORT: {{ .Values.backend.service.port | quote }}
  FRONTEND_SERVICE_HOST: {{ include "todo-chatbot.component.fullname" (list "frontend" .) }}
  FRONTEND_SERVICE_PORT: {{ .Values.frontend.service.port | quote }}
{{- end }}